# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 97cc1ffc373a0a6c8a779788f56cd3a2da1cbab7d198b8b929091748f98f2920258e5db3d82ce471f40b3a7392d82bd0490cfd970bea5fccb748d022cb43bde7

test:
  secret_key_base: f6710d2364724a939271d0a9fc07dc0e0de5a88a06dd1b9455b30bc76178981970004aca5af23f9ddcc75a339dd935e60412257609dc519e47c9b1d167ac5d62

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
